sd_url: http://127.0.0.1:7860
base_prompt: <lora:ComicStyleXL:1> (artstyle, jed-cmc)
characters_models:
  Elisa: <lora:elisa_model:1.3> (elisa, blue eyes, glasses), ((plain pink shirt)) 
  Professor Thompson: <lora:lucaia_model:1.3> (luca, brown eyes, glasses, beard), ((plain red shirt)) 
sd_payload:
  cfg_scale: 7
  denoising_strength: 0.7
  negative_prompt: ((realistic)), speaches, text baloons, speach baloons
  override_settings:
    sd_model_checkpoint: juggernautXL_juggXIByRundiffusion.safetensors
  sampler_name: Euler a
  scheduler: Karras
  height: 512
  steps: 35
  width: 512
  clip_skip: 1
  enable_hr: true
  hr_sampler_name: Euler a
  hr_scale: 2
  hr_upscaler: Latent
llm_model:
  model: gemma3:latest
  model_info:
    vision: true
    function_calling: false
    json_output: false
    family: gemma3
  host: 127.0.0.1
  port: 11434
# llm_model:
#   model: gemma3:27b
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 87.166.24.53
#   port: 11434




##### senza hres.fix #####

# sd_url: http://127.0.0.1:7860
# base_prompt: (solo), <lora:ComicStyleXL:1> ((artstyle, jed-cmc))
# characters_models:
#   Elisa: <lora:elisa_model:1.3> (elisa, girl, little)
#   Professor Thompson: <lora:lucaia_model:1.3> (luca, man, black hair, beard)
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: ((realistic)), speaches, text baloons, speach baloons
#   override_settings:
#     sd_model_checkpoint: juggernautXL_juggXIByRundiffusion.safetensors
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512

###### con refiner ######

# sd_url: http://127.0.0.1:7860
# base_prompt: (solo), <lora:ComicStyleXL:1> ((artstyle, jed-cmc))
# characters_models:
#   Elisa: <lora:elisa_model:1.3> (elisa, girl, little)
#   Professor Thompson: <lora:lucaia_model:1.3> (luca, man, black hair, beard)
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: ((realistic)), speaches, text baloons, speach baloons
#   override_settings:
#     sd_model_checkpoint: juggernautXL_juggXIByRundiffusion.safetensors
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512
#   enable_hr: true
#   hr_sampler_name: Euler a
#   hr_scale: 2
#   hr_upscaler: Latent
#   refiner_checkpoint: sd_xl_refiner_1.0.safetensors
#   refiner_switch_at: 0.8
#   restore_faces: true

###### mistoonAnime ######

# sd_url: http://127.0.0.1:7860
# base_prompt: (((solo)))
# characters_models:
#   Elisa: <lora:elisaia_v1-5:1> (elisaia, girl, little, glasses)
#   Professor Thompson: <lora:lucaia_v1-5:1> (lucaia, man, glasses, beard),((plain red shirt)) 
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: speaches, text baloons, speach baloons, bad anatomy, bad hands, three hands, three legs, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, worst face, out of frame double, three crus, extra crus, fused crus, worst feet, three feet, fused feet, fused thigh, three thigh, extra thigh, worst thigh, missing fingers, extra fingers, ugly fingers, long fingers, horn, realistic photo, extra eyes, huge eyes, 2girl, 2boy, amputation, disconnected limbs
#   override_settings:
#     sd_model_checkpoint: mistoonAnime_v30.safetensors
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512
#   enable_hr: true
#   hr_sampler_name: Euler a
#   hr_scale: 2
#   hr_upscaler: Latent
# llm_model:
#   model: gemma3:latest
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 127.0.0.1
#   port: 11434

##### Gemma 27b #####

# llm_model:
#   model: gemma3:27b
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 127.0.0.1
#   port: 11434

# dreamshaper_8.safetensors

# sd_url: http://127.0.0.1:7860
# base_prompt: (((solo)))
# characters_models:
#   Elisa: <lora:elisaia_v1-5:1> (elisaia, girl, little, glasses)
#   Professor Thompson: <lora:lucaia_v1-5:1> (lucaia, man, glasses, beard),((plain red shirt)) 
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: speaches, text baloons, speach baloons, bad anatomy, bad hands, three hands, three legs, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, worst face, out of frame double, three crus, extra crus, fused crus, worst feet, three feet, fused feet, fused thigh, three thigh, extra thigh, worst thigh, missing fingers, extra fingers, ugly fingers, long fingers, horn, realistic photo, extra eyes, huge eyes, 2girl, 2boy, amputation, disconnected limbs
#   override_settings:
#     sd_model_checkpoint: dreamshaper_8.safetensors
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512
#   enable_hr: true
#   hr_sampler_name: Euler a
#   hr_scale: 2
#   hr_upscaler: Latent
# llm_model:
#   model: gemma3:latest
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 127.0.0.1
#   port: 11434

# anythingV3_fp16

# sd_url: http://127.0.0.1:7860
# base_prompt: (((solo)))
# characters_models:
#   Elisa: <lora:elisaia_v1-5:1> (elisaia, girl, little, glasses)
#   Professor Thompson: <lora:lucaia_v1-5:1> (lucaia, man, glasses, beard),((plain red shirt)) 
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: speaches, text baloons, speach baloons, bad anatomy, bad hands, three hands, three legs, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, worst face, out of frame double, three crus, extra crus, fused crus, worst feet, three feet, fused feet, fused thigh, three thigh, extra thigh, worst thigh, missing fingers, extra fingers, ugly fingers, long fingers, horn, realistic photo, extra eyes, huge eyes, 2girl, 2boy, amputation, disconnected limbs
#   override_settings:
#     sd_model_checkpoint: anythingV3_fp16
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512
#   enable_hr: true
#   hr_sampler_name: Euler a
#   hr_scale: 2
#   hr_upscaler: Latent
# llm_model:
#   model: gemma3:latest
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 127.0.0.1
#   port: 11434

# arthemyComics_v70

# sd_url: http://127.0.0.1:7860
# base_prompt: (((solo)))
# characters_models:
#   Elisa: <lora:elisaia_v1-5:1> (elisaia, girl, little, glasses)
#   Professor Thompson: <lora:lucaia_v1-5:1> (lucaia, man, glasses, beard),((plain red shirt)) 
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: speaches, text baloons, speach baloons, bad anatomy, bad hands, three hands, three legs, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, worst face, out of frame double, three crus, extra crus, fused crus, worst feet, three feet, fused feet, fused thigh, three thigh, extra thigh, worst thigh, missing fingers, extra fingers, ugly fingers, long fingers, horn, realistic photo, extra eyes, huge eyes, 2girl, 2boy, amputation, disconnected limbs
#   override_settings:
#     sd_model_checkpoint: arthemyComics_v70
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512
#   clip_skip: 2
#   enable_hr: true
#   hr_sampler_name: Euler a
#   hr_scale: 2
#   hr_upscaler: Latent
# llm_model:
#   model: gemma3:latest
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 127.0.0.1
#   port: 11434

# flat2DAnimerge_v45Sharp

# sd_url: http://127.0.0.1:7860
# base_prompt: (((solo)))
# characters_models:
#   Elisa: <lora:elisaia_v1-5:1> (elisaia, girl, little, glasses)
#   Professor Thompson: <lora:lucaia_v1-5:1> (lucaia, man, glasses, beard),((plain red shirt)) 
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: speaches, text baloons, speach baloons, bad anatomy, bad hands, three hands, three legs, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, worst face, out of frame double, three crus, extra crus, fused crus, worst feet, three feet, fused feet, fused thigh, three thigh, extra thigh, worst thigh, missing fingers, extra fingers, ugly fingers, long fingers, horn, realistic photo, extra eyes, huge eyes, 2girl, 2boy, amputation, disconnected limbs
#   override_settings:
#     sd_model_checkpoint: flat2DAnimerge_v45Sharp
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512
#   clip_skip: 2
#   enable_hr: true
#   hr_sampler_name: Euler a
#   hr_scale: 2
#   hr_upscaler: Latent
# llm_model:
#   model: gemma3:latest
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 127.0.0.1
#   port: 11434

# toonyou_beta6

# sd_url: http://127.0.0.1:7860
# base_prompt: (((solo)))
# characters_models:
#   Elisa: <lora:elisaia_v1-5:1> (elisaia, girl, little, glasses)
#   Professor Thompson: <lora:lucaia_v1-5:1> (lucaia, man, glasses, beard),((plain red shirt)) 
# sd_payload:
#   cfg_scale: 7
#   denoising_strength: 0.7
#   height: 512
#   negative_prompt: speaches, text baloons, speach baloons, bad anatomy, bad hands, three hands, three legs, bad arms, missing legs, missing arms, poorly drawn face, bad face, fused face, cloned face, worst face, out of frame double, three crus, extra crus, fused crus, worst feet, three feet, fused feet, fused thigh, three thigh, extra thigh, worst thigh, missing fingers, extra fingers, ugly fingers, long fingers, horn, realistic photo, extra eyes, huge eyes, 2girl, 2boy, amputation, disconnected limbs
#   override_settings:
#     sd_model_checkpoint: toonyou_beta6
#   sampler_name: Euler a
#   scheduler: Karras
#   steps: 35
#   width: 512
#   clip_skip: 2
#   enable_hr: true
#   hr_sampler_name: Euler a
#   hr_scale: 2
#   hr_upscaler: Latent
# llm_model:
#   model: gemma3:latest
#   model_info:
#     vision: true
#     function_calling: false
#     json_output: false
#     family: gemma3
#   host: 127.0.0.1
#   port: 11434